name: Build and push to GHCR
on:
  push:
    branches:
      - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 'Login to GitHub Container Registry'
        run: |
          set -xe
          docker login --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} ghcr.io

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: server/Dockerfile
          push: true
          cache-from: type=registry,ref=ghcr.io/coqui-ai/xtts-streaming-server:latest
          cache-to: type=registry,ref=ghcr.io/coqui-ai/xtts-streaming-server:latest
          tags: coqui-ai/xtts-streaming-server:latest
          #build-args:
